import './style.css'
import Notification from "@/app/components/Dashboard/Notifications/Notification";

export const metadata = {
  title: "Notifications - Hr Portal",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Notification/>
  );
};

export default page;
