import './style.css'
import Wrapper from "@/app/components/Ui/Wrapper/Wrapper";
import Container from "@/app/components/Ui/DashboardContainer/Container";
import RecentNotifications from "@/app/components/Dashboard/Notifications/RecentNotifications";
import AddNotification from "@/app/components/Dashboard/Notifications/AddNotification";



export const metadata = {
  title: "Employee Data - Hr Portal",
  description: "Generated by create next app",
};

const page = () => {
  return (
 <>
 <Container heading='Notifications'>
  <Wrapper className='flex justify-between gap-[15px]'>
  <RecentNotifications/>
  <AddNotification/>
 </Wrapper>
 </Container>
 </>
  );
};

export default page;
