import Leaves from "@/app/components/Dashboard/Leaves/Leaves";
export const metadata = {
  title: "Leaves - Hr Portal",
  description: "Generated by create next app",
};
const page = () => {
  return <Leaves />;
};

export default page;
