import Team from "@/app/components/Dashboard/Team/Team";

export const metadata = {
    title: "My Team - Hr Portal",
    description: "Generated by create next app",
  };
  
const page = () => {
  return (
    <Team/>
  );
}

export default page;
