import AllEmployees from "@/app/components/Dashboard/Employees/AllEmployees";
import AddEmployee from "@/app/components/Form/AddEmployee/AddEmployee";
import Wrapper from "@/app/components/Ui/Wrapper/Wrapper";
import Container from "@/app/components/Ui/DashboardContainer/Container";
import AccessDenied from "@/app/components/Ui/AccessDenied/AccessDenied";

export const metadata = {
  title: "Employee Data - Hr Portal",
  description: "Generated by create next app",
};

const page = () => {
  return (
 <>
 <Container heading='Employees'>
  <Wrapper className='flex justify-between gap-[15px] mb-5'>
  <AllEmployees/>
  <AddEmployee/>
  <AccessDenied permission='read-employees' message='View Employees'/>
 </Wrapper>
 </Container>
 </>
  );
};

export default page;
