import AddEmployee from "@/app/components/Form/AddEmployee/AddEmployee";

export const metadata = {
  title: "Employee Data - Hr Portal",
  description: "Generated by create next app",
};

const page = () => {
  return (
 <>
 <AddEmployee/>
 </>
  );
};

export default page;
