import Department from "@/app/components/Dashboard/Departments/Department";

export const metadata = {
    title: "Departments - Hr Portal",
    description: "Generated by create next app",
  };
  
const page = () => {
  return (
    <Department/>
  );
}

export default page;
