import Designation from "@/app/components/Dashboard/Designation/Designation";

export const metadata = {
    title: "Designations - Hr Portal",
    description: "Generated by create next app",
  };
  
const page = () => {
  return (
    <Designation/>
  );
}

export default page;
