import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeConfiger } from "./contexts/theme/ThemeConfigure";
import { GetSession } from "./api/auth/sign-in/route";
import GetUserData from "./components/auth/GetUser";
import { AuthProvider } from "./contexts/Auth/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await GetSession(); 
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeConfiger>        
      <AuthProvider>
      <GetUserData session={JSON.stringify(session)}></GetUserData>
        {children}
        </AuthProvider>
      </ThemeConfiger>
      </body>
    </html>
  );
}
