import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeConfiger } from "./contexts/theme/ThemeConfigure";
import { GetSession } from "./api/auth/sign-in/route";
import GetUserData from "./components/auth/GetUser";
import { AuthProvider } from "./contexts/Auth/auth";
import Sidebar from "./layouts/Sidebar/Sidebar";
import Header from "./layouts/Header/Header";
import Birthday from "./components/Modals/Birthday/Birthday";
import { DashboardConfiger } from "./contexts/Dashboard/dashboard";
import { SocketProvider } from "./contexts/Socket/SocketContext";
import RealtimeNotification from "./components/Ui/RealtimeNotification/RealtimeNotification";
import Increment from "./components/Modals/Increment/Increment";
import Wrapper from "./components/Ui/Wrapper/Wrapper";
import Main from "./components/Ui/Main/Main";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HR Portal - Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await GetSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeConfiger>
          <DashboardConfiger>
            <AuthProvider>
              <SocketProvider>
                <Main>
                  <GetUserData session={JSON.stringify(session)}></GetUserData>
                  <Sidebar />
                  <Header />
                  {children}
                  <Birthday />
                  <Increment />
                  <RealtimeNotification />
                </Main>
              </SocketProvider>
            </AuthProvider>
          </DashboardConfiger>
        </ThemeConfiger>
      </body>
    </html>
  );
}
