import Index from "./sections/dashboard/view";


export const metadata = {
  title: "Home - HR Portal",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <>
      <Index />
    </>
  );
}
