import Holidays from "@/app/components/Dashboard/Holidays/Holidays";
import React from "react";
export const metadata = {
  title: "Holidays - Hr Portal",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <Holidays />
    </div>
  );
};

export default page;
