import Roles from "@/app/components/Dashboard/Roles/Roles";

export const metadata = {
    title: "Roles - Hr Portal",
    description: "Generated by create next app",
  };
  
const page = () => {
  return <Roles />;
};

export default page;
