import Salary from '@/app/components/Dashboard/Salary/Salary';
import './style.css';
export const metadata = {
  title: "Salary - Hr Portal",
  description: "Generated by create next app",
};
const page = () => {
  return (
   <Salary/>
  )
}

export default page
